worker_processes auto;

events {
  worker_connections 1024;
}

http {
  log_format backend_gateway_log '[$time_local] [BACKEND-API-GATEWAY] $remote_addr - "$request" -> Microservice Upstream: $upstream_addr (Status: $status, Time: ${upstream_response_time}s)';
  access_log /dev/stdout backend_gateway_log;

  proxy_connect_timeout 5s;
  proxy_send_timeout 30s;
  proxy_read_timeout 30s;
  proxy_http_version 1.1;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  # Enrutamiento dinámico centralizado a microservicios del Backend
  server {
    listen 8080;
    server_name localhost;

    location = /health {
      default_type application/json;
      return 200 '{"status":"UP","service":"backend-api-gateway","discovery":"eureka:8761"}';
    }

    # Regla 4 de la lámina: Enruta hacia MS Usuarios (PostgreSQL)
    location /usuarios {
      proxy_pass http://usuarios-service:8080;
    }

    # Regla 4 de la lámina: Enruta hacia MS Productos (PostgreSQL)
    location /productos {
      proxy_pass http://productos-service:8081;
    }
  }
}
